#!/bin/sh
ssh ubuntu@10.118.10.25 <<EOF
    cd ~/express-long-polling
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v12.19.0
    npm install
    npm install -g nodemon pm2 forever
    forever start server.js
    exit
EOF
