#!/bin/sh
ssh ubuntu@10.118.10.25 <<EOF
    cd ~/express-pm2-long-polling
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v12.19.0
    npm install
    npm install -g pm2

    pm2 reload pm2.config.js
    exit
EOF
